name: kanban

windows:
  - main:
      panes:
          - cd $(ghq root)/github.com/yuyu-hf/tmuxcc/tui && node ./dist/index.js
  - tmuxcc-dev:
      layout: even-horizontal
      panes:
          - cd $(ghq root)/github.com/yuyu-hf/tmuxcc && tmuxcc start
          - cd $(ghq root)/github.com/yuyu-hf/tmuxcc && docker compose up
