# Ref: https://namileriblog.com/terminal/terminal_setting_starship/

add_newline = true

format = """
[](fg:#7aa2f7)\
$os\
[ ](fg:#7aa2f7 bg:#1a1b26)\
$directory\
$git_branch\
$git_status\
$git_metrics\
[](fg:#1a1b26)\
$fill\
([](fg:#1a1b26)$nodejs[](fg:208 bg:#1a1b26)$package)\
([](fg:#1a1b26)$golang(bg:#1a1b26))\
([](fg:#1a1b26)$rust(bg:#1a1b26))\
([](fg:#1a1b26)$python(bg:#1a1b26))\
\n$character\
"""

right_format = """
$cmd_duration
$time
"""

[os]
format = "[$symbol]($style)"
style = 'fg:#1a1b26 bg:#7aa2f7'
disabled = false

[os.symbols]
Macos = "  " # nf-fa-apple
Ubuntu = "  " # nf-linux-ubuntu
Debian = "  " # nf-linux-debian

[directory]
truncation_length = 6
truncation_symbol = ' ' # nf-fa-folder_open
truncate_to_repo = false
home_symbol = ' ~' # nf-costum-home
style = 'fg:#7aa2f7 bg:#1a1b26'
read_only = ' 󰌾 ' # nf-md-lock
read_only_style = 'fg:#f7768e bg:#1a1b26'
format = '[$path]($style)[$read_only]($read_only_style)'

[git_branch]
symbol = ' ' # nf-fa-github_alt, nf-fa-code_fork
truncation_length = 4
truncation_symbol = ''
style = 'fg:#7aa2f7 bg:#1a1b26'
format = '[  $symbol$branch(:$remote_branch)]($style)' # nf-pl-left_soft_divider

[git_status]
style = 'fg:#e0af68 bg:#1a1b26'
conflicted = '='
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕'
up_to_date = '✓'
untracked = '?'
stashed = '$'
modified = '!${count}'
renamed = '»'
deleted = '✘'
format = '([\[$all_status$ahead_behind\]]($style))'

[git_metrics]
disabled = false
format = '[+$added/-$deleted]($deleted_style)'
added_style = 'fg:#9ece6a bg:#1a1b26'
deleted_style = 'fg:#9ece6a bg:#1a1b26'

[fill]
symbol = '─'
style = 'blue'

[nodejs]
symbol = " " # nf-dev-nodejs
style = 'fg:#9ece6a bg:#1a1b26'
format = '[via $symbol($version )]($style)'

[golang]
symbol = "  󰟓 "
style = "fg:#79d4fd bg:#1a1b26"
format = '[via $symbol($version )]($style)'

[package]
style = 'fg:#000000 bg:208'
format = '[via $symbol($version )]($style)'
display_private = true

[cmd_duration]
min_time = 500
style = 'fg:#e0af68'
format = "[   $duration]($style)" # nf-pl-right_soft_divider, nf-mdi-clock

[time]
disabled = false
style = 'fg:#73daca'
format = '[   $time]($style)' # nf-pl-right_soft_divider, nf-fa-clock_o
time_format = '%T'
utc_time_offset = '+9'

[aws]
disabled = true

[gcloud]
disabled = true
