---
checksum:
  enabled: true
  require_checksum: false
  supported_envs:
  - all
registries:
- type: standard
  ref: v4.462.0
packages:
  # shell
  - name: starship/starship@v1.24.2
  # git
  - name: cli/cli@v2.83.2
  - name: x-motemen/ghq@v1.8.0
  # neovim
  - name: neovim/neovim@v0.11.5
  # python
  - name: astral-sh/uv@0.9.21
  # Lua
  - name: JohnnyMorganz/StyLua@v2.3.1
  - name: LuaLS/lua-language-server@3.16.4
  # DB
  - name: duckdb/duckdb@v1.4.3
  # Cloud Service
  - name: aws/aws-cli@2.33.5
  - name: stripe/stripe-cli@v1.34.0
  # AI
  - name: anthropics/claude-code@v2.1.17
  - name: openai/codex@rust-v0.89.0
  # tool
  - name: jqlang/jq@jq-1.8.1
  - name: ajeetdsouza/zoxide@v0.9.8
  - name: sxyazi/yazi@v26.1.4
  - name: junegunn/fzf@v0.67.0
  - name: BurntSushi/ripgrep@15.1.0
  - name: sharkdp/bat@v0.26.1
  - name: eza-community/eza@v0.23.4
  - name: sharkdp/fd@v10.3.0
  - name: tree-sitter/tree-sitter@v0.26.3
